name: CD

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/iwvg-devops-2026-${{ steps.extract_branch.outputs.BRANCH_NAME }}:latest

  cd:
    name: Deploy Docker Postgres on AWS Lightsail
    needs: build-and-push
    runs-on: ubuntu-22.04
    steps:
      - name: 🚀 Deploy on AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          script: |
            docker rm -f postgres || true
            docker network create devopsNet || true
            docker run -d \
              --name postgres \
              --restart always \
              --network devopsNet \
              -p 5432:5432 \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=iwvgdevopsdb \
              postgres:15.10